<?php
// $Id$
/**
 * @file
 * API of commonly needed services, like centralized authentication.
 */


/**
 * Implementation of hook_help()
 */
function cul_common_help($path, $arg) {
    if ($path == 'admin/help#cul_common') {
        $txt = 'API of commonly needed services, like centralized authentication.';
    }
    return '<p>' . t($txt) . '</p>';
}

/**
 * Basic authentication method, redirects to a CUWebAuth protected directory,
 * and upon successful authentication, it will set a 'netid' cookie.
 */
function cu_authenticate() {
  if (isset($_COOKIE['netid'])) {
    return $_COOKIE['netid'];
  } else {
    drupal_goto(drupal_get_path('module', 'cul_common') . '/authenticate', drupal_get_destination());
  }
}

/**
 * Implementation of hook_view()
 */
function cul_common_view($node, $teaser=FALSE, $page=FALSE) {
  // TODO: need to start with a check of the node field injected
  if (! isset($_COOKIE['netid'])) {
    cu_authenticate();
  }
  return $node;
}


